
---
# This will scan linux systems for JBoss Fuse, ActiveMQ, CXF, Camel or Community  Installations
    - name: Gather activemq-ver
      raw: FOUND=""; for jar in `find / -type f -name \*activemq-\*redhat\*.jar 2>/dev/null | sed -n 's/.*\(redhat-[0-9]\{6\}\).*/\1/p' | sort -u`; do if [ ! -z "${jar}" ]; then if [ ! -z "$FOUND" ]; then FOUND="$FOUND; $jar"; else FOUND=${jar}; fi; fi; done; echo ${FOUND}
      register: activemq-ver
      ignore_errors: yes
    - name: Gather camel-ver
      raw: FOUND=""; for jar in `find / -type f -name \*camel-core\*redhat\*.jar 2>/dev/null | sed -n 's/.*\(redhat-[0-9]\{6\}\).*/\1/p' | sort -u`; do if [ ! -z "${jar}" ]; then if [ ! -z "$FOUND" ]; then FOUND="$FOUND; $jar"; else FOUND=${jar}; fi; fi; done; echo ${FOUND}
      register: camel-ver
      ignore_errors: yes
    - name: Gather cxf-ver
      raw: FOUND=""; for jar in `find / -type f -name \*cxf-rt\*redhat\*.jar 2>/dev/null | sed -n 's/.*\(redhat-[0-9]\{6\}\).*/\1/p' | sort -u`; do if [ ! -z "${jar}" ]; then if [ ! -z "$FOUND" ]; then FOUND="$FOUND; $jar"; else FOUND=${jar}; fi; fi; done; echo ${FOUND}
      register: cxf-ver
      ignore_errors: yes
    #- name: set facts
    #  ignore_errors: yes
    #  set_fact:
    #    res:
    #     {installed_versions: "{{ kie-api-ver.stdout }}; {{ runjar_ver.stdout }}", running_versions: "{{ running_versions.stdout }}", hostname: "{{ hostname.stdout }}", cpu_cores: "{{ cpu_cores.stdout }}"}

